default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: 192.168.1.139
  database: record-player-service-db
  username: admin
  password: password123

development:
  <<: *default

production:
  <<: *default